name: flutter_application_1
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_native_splash: ^2.2.6
  geolocator: ^9.0.2
  shimmer: ^2.0.0
  connectivity_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_native_splash:
  color: '#ffffff'
  image: assets/images/brightness.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  color_dark: '#ffffff'
  background_image_dark: assets/images/brightness.png

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/direction.png
    - assets/images/search.png
    - assets/images/humidity.png
    - assets/images/precipitation.png
    - assets/images/rain.png
    - assets/images/up-arrow.png
    - assets/images/uv.png
    - assets/images/visibility.png
    - assets/images/wind.png
    - assets/images/sunrise.png
    - assets/images/sunset.png
    - assets/images/no-internet.png
    - assets/images/day/113.png
    - assets/images/day/116.png
    - assets/images/day/119.png
    - assets/images/day/122.png
    - assets/images/day/143.png
    - assets/images/day/176.png
    - assets/images/day/179.png
    - assets/images/day/182.png
    - assets/images/day/185.png
    - assets/images/day/200.png
    - assets/images/day/227.png
    - assets/images/day/230.png
    - assets/images/day/248.png
    - assets/images/day/260.png
    - assets/images/day/263.png
    - assets/images/day/266.png
    - assets/images/day/281.png
    - assets/images/day/284.png
    - assets/images/day/293.png
    - assets/images/day/296.png
    - assets/images/day/299.png
    - assets/images/day/302.png
    - assets/images/day/305.png
    - assets/images/day/308.png
    - assets/images/day/311.png
    - assets/images/day/314.png
    - assets/images/day/317.png
    - assets/images/day/320.png
    - assets/images/day/323.png
    - assets/images/day/326.png
    - assets/images/day/329.png
    - assets/images/day/332.png
    - assets/images/day/335.png
    - assets/images/day/338.png
    - assets/images/day/350.png
    - assets/images/day/353.png
    - assets/images/day/356.png
    - assets/images/day/359.png
    - assets/images/day/362.png
    - assets/images/day/365.png
    - assets/images/day/368.png
    - assets/images/day/371.png
    - assets/images/day/374.png
    - assets/images/day/377.png
    - assets/images/day/386.png
    - assets/images/day/389.png
    - assets/images/day/392.png
    - assets/images/day/395.png
    - assets/images/night/113.png
    - assets/images/night/116.png
    - assets/images/night/119.png
    - assets/images/night/122.png
    - assets/images/night/143.png
    - assets/images/night/176.png
    - assets/images/night/179.png
    - assets/images/night/182.png
    - assets/images/night/185.png
    - assets/images/night/200.png
    - assets/images/night/227.png
    - assets/images/night/230.png
    - assets/images/night/248.png
    - assets/images/night/260.png
    - assets/images/night/263.png
    - assets/images/night/266.png
    - assets/images/night/281.png
    - assets/images/night/284.png
    - assets/images/night/293.png
    - assets/images/night/296.png
    - assets/images/night/299.png
    - assets/images/night/302.png
    - assets/images/night/305.png
    - assets/images/night/308.png
    - assets/images/night/311.png
    - assets/images/night/314.png
    - assets/images/night/317.png
    - assets/images/night/320.png
    - assets/images/night/323.png
    - assets/images/night/326.png
    - assets/images/night/329.png
    - assets/images/night/332.png
    - assets/images/night/335.png
    - assets/images/night/338.png
    - assets/images/night/350.png
    - assets/images/night/353.png
    - assets/images/night/356.png
    - assets/images/night/359.png
    - assets/images/night/362.png
    - assets/images/night/365.png
    - assets/images/night/368.png
    - assets/images/night/371.png
    - assets/images/night/374.png
    - assets/images/night/377.png
    - assets/images/night/386.png
    - assets/images/night/389.png
    - assets/images/night/392.png
    - assets/images/night/395.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
